BOTOCORE_EXPERIMENTAL__PLUGINS=S3AccessGrantsPlugin=aws_s3_access_grants_boto3_plugin.s3_access_grants_plugin
cd ~
DOMAIN_MODE=EXPRESS
readonly DOMAIN_MODE
SMUS_PROJECT_DIR=/home/sagemaker-user/shared
readonly SMUS_PROJECT_DIR
LOGNAME=arn:aws:iam::360168612390:root
readonly LOGNAME
export AMAZON_Q_SIGV4=true
export Q_CLI_CLIENT_APPLICATION=SMUS_JUPYTER_LAB_EXPRESS
readonly Q_CLI_CLIENT_APPLICATION
